name: Test
on:
  push: {}
  pull_request:
    types: [opened, synchronize]
jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      - name: Show repository content
        run: ls -la
